[project]
name = "delta-policy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mujoco>=3.5.0",
    "onshape-to-robot>=1.8.1",
    "pybullet>=3.2.7",
]
